=== bmarrao/mestrado/PDE/Prática/Trabalho/receitasAtrib.dtd
<!ELEMENT receitas  (cabecalho, parte+)>
<!ELEMENT cabecalho  (titulo, autor+, data-publicacao,  resumo?)>
<!ELEMENT resumo  (#PCDATA)>
<!ELEMENT autor  (#PCDATA)>
<!ELEMENT data-publicacao  (ano, mes, dia)>
<!ELEMENT ano  (#PCDATA)>
<!ELEMENT mes  (#PCDATA)>
<!ELEMENT dia  (#PCDATA)>
<!ELEMENT titulo  (#PCDATA)>
<!ELEMENT texto-introdutorio  (#PCDATA)>
<!ELEMENT parte (titulo,texto-introdutorio?,(receita | seção)*)>
<!ATTLIST parte
        image           CDATA #IMPLIED>
<!ELEMENT seção (titulo,texto-introdutorio?,(receita | sub-seção)*) >
<!ATTLIST seção
        image           CDATA #IMPLIED>
<!ELEMENT sub-seção (titulo,texto-introdutorio?,receita*) >
<!ATTLIST sub-seção
        image           CDATA #IMPLIED>
<!ELEMENT receita (nome, calorias, (#PCDATA,ingrediente,#PCDATA?)+ , (passo| #PCDATA)*) >
<!ATTLIST receita
        id              ID    #IMPLIED
        categoria       (entrada | sobremesa | prato-principal) #IMPLIED
        dificuldade     (simples | médio | díficil) #IMPLIED
        tempo           (rápido | médio | lento) #IMPLIED
        custo           (barato | médio | caro) #IMPLIED
        image        CDATA #IMPLIED>
<!ELEMENT ingrediente (nome+, quantidade, unidade-medida) >
<!ATTLIST ingediente
        id     ID       #IMPLIED>
<!ELEMENT quantidade (#PCDATA) >
<!ELEMENT nome (#PCDATA)>
<!ELEMENT calorias (#PCDATA)>
<!ELEMENT unidade-medida (#PCDATA)>
<!ELEMENT passo (#PCDATA) >
<!ATTLIST passo
        ilustracao         ID       #IMPLIED>

=== bmarrao/mestrado/PDE/Prática/Trabalho/exempoDTD.xml
<?xml version="1.0" encoding="ISO-8859-1"?>
<!DOCTYPE receitas SYSTEM "receitasAtrib.dtd">
<receitas>
    <cabecalho>
        <titulo>Livro de receitas do Breno</titulo>
        <autor>Breno Fernando Guerra Marrão</autor>
        <autor>Se quiser posso adicionar outros autores</autor>
        <data-publicacao>
            <ano>2023</ano>
            <mes>10</mes>
            <dia>8</dia>
        </data-publicacao>
        <resumo>
            Esse é o resumo opcional
        </resumo>
    </cabecalho>

    <parte image="uri">
        <titulo>Comida italiana</titulo>
        <texto-introdutorio>Esse é o texto-introdutorio opcional</texto-introdutorio>
        <receita nome="Spaghetti">
            <!-- aqui irei adicionar uma receita como exemplo -->
            <ingrediente>
                <nome>
                    spaghetti
                </nome>
                <!-- Opcional -->

                <quantidade>
                    100
                </quantidade>
                <!-- Opcional -->

                <unidade-medida>
                    gramas
                </unidade-medida>

            </ingrediente>
            Posso também escrever algo ou antes de um ingrediente para fornecer um pouco de contexto
            <ingrediente >
                <nome>Molho </nome>
                <quantidade>100</quantidade>
                <unidade-medida>ml</unidade-medida>
            </ingrediente>
            Antes e depois dos passos também
            <passo>
                Colocar agua na panela
            </passo>
            Posso fazer entre passos também
            <passo>
                Colocar macarrão na agua fervendo
            </passo>
        </receita>
    </parte>

</receitas>
