=== bmarrao/mestrado/PDE/Prática/Trabalho/receitas.xsd
<?xml version="1.0" encoding="UTF-8"?>
<xs:schema
        xmlns:xs="http://www.w3.org/2001/XMLSchema"
        elementFormDefault="qualified"
        targetNamespace="receitas"
        xmlns:receitas="receitas"
        >

    <xs:element name="categoria">
        <xs:simpleType>
            <xs:restriction base="xs:string">
                <xs:enumeration value="entrada"/>
                <xs:enumeration value="sobremesa"/>
                <xs:enumeration value="prato-principal"/>
            </xs:restriction>
        </xs:simpleType>
    </xs:element>

    <xs:element name="dificuldade">
        <xs:simpleType>
            <xs:restriction base="xs:string">
                <xs:pattern value="simples | médio | díficil"/>
            </xs:restriction>
        </xs:simpleType>
    </xs:element>

    <xs:element name="tempo">
        <xs:simpleType>
            <xs:restriction base="xs:string">
                <xs:pattern value="rápido | médio | lento"/>
            </xs:restriction>
        </xs:simpleType>
    </xs:element>

    <xs:element name="custo">
        <xs:simpleType>
            <xs:restriction base="xs:string">
                <xs:pattern value="barato | médio | caro"/>
            </xs:restriction>
        </xs:simpleType>
    </xs:element>


    <xs:element name="data-publicacao" type="xs:date"/>
    <xs:element name="ilustração" type="xs:anyURI"/>
    <xs:element name="resumo" type="xs:string"/>
    <xs:element name="titulo" type="xs:string"/>
    <xs:element name="texto-introdutorio" type="xs:string"/>
    <xs:element name="autor" type="xs:string"/>
    <xs:element name="nome" type="xs:string"/>
    <xs:element name="unidade-medida" type="xs:string"/>
    <xs:element name="calorias" type="xs:int"/>
    <xs:element name="quantidade" type="xs:int"/>
    <xs:element name="texto" type="xs:string"/>

    <xs:element name="ingredienteRef" type="xs:string"/>



    <xs:element name="passoRef">
        <xs:complexType>
            <xs:attribute name="ref" type="xs:IDREF"/>
        </xs:complexType>
    </xs:element>

    <xs:element name="cabecalho">
        <xs:complexType>
            <xs:sequence>
                <xs:element ref="receitas:titulo"/>
                <xs:element ref="receitas:autor" maxOccurs="unbounded" />
                <xs:element ref="receitas:data-publicacao"/>
                <xs:element ref="receitas:resumo"  minOccurs="0"/>
            </xs:sequence>
        </xs:complexType>
    </xs:element>

    <xs:element name="ingrediente">
        <xs:complexType>
            <xs:sequence>
                <xs:element ref="receitas:nome"/>
                <xs:element ref="receitas:quantidade" minOccurs="0"/>
                <xs:element ref="receitas:unidade-medida" minOccurs="0"/>
            </xs:sequence>
            <xs:attribute name="id" type="xs:ID" use="required"/>
        </xs:complexType>
    </xs:element>

    <xs:element name="ingredientes">
        <xs:complexType>
            <xs:sequence>
                <xs:element ref="receitas:ingrediente" maxOccurs="unbounded"/>
            </xs:sequence>
        </xs:complexType>
    </xs:element>

    <xs:element name="instruções">
        <xs:complexType mixed="true">
            <xs:choice>
                <!-- talvez de erro mixed="true" -->
                <xs:choice maxOccurs="unbounded" >
                    <xs:element ref="receitas:passo"/>
                    <xs:element ref="receitas:passoRef"/>
                    <xs:element ref="receitas:receitaRef"/>
                </xs:choice>
                <xs:choice maxOccurs="unbounded" >
                    <xs:element ref="receitas:receitaRef"/>
                    <xs:element ref="receitas:ingredienteRef"/>
                </xs:choice>
            </xs:choice>
        </xs:complexType>
    </xs:element>

    <xs:element name="receita">
        <xs:complexType>
            <xs:sequence>
                <xs:element ref="receitas:nome"/>
                <xs:element ref="receitas:calorias"  minOccurs="0"/>
                <xs:element ref="receitas:categoria" minOccurs="0"/>
                <xs:element ref="receitas:dificuldade" minOccurs="0"/>
                <xs:element ref="receitas:tempo" minOccurs="0"/>
                <xs:element ref="receitas:custo" minOccurs="0"/>
                <xs:element ref="receitas:ilustração" minOccurs="0"/>
                <xs:element ref="receitas:ingredientes" maxOccurs="1" />
                <xs:element ref="receitas:instruções" maxOccurs="1"/>
            </xs:sequence>
            <xs:attribute name="id" type="xs:ID" />

        </xs:complexType>
    </xs:element>

    <xs:element name="receitaRef">
        <xs:complexType>
            <xs:attribute name="ref" type="xs:IDREF"/>
        </xs:complexType>
    </xs:element>

    <xs:element name="sub-seção">
        <xs:complexType>
            <xs:sequence>
                <xs:element ref="receitas:titulo"/>
                <xs:element ref="receitas:texto-introdutorio"  minOccurs="0"/>
                <xs:element ref="receitas:ilustração" minOccurs="0"/>
                <xs:element ref="receitas:receita"  maxOccurs="unbounded"/>
            </xs:sequence>
        </xs:complexType>
    </xs:element>

    <xs:element name="seção">
        <xs:complexType>
            <xs:sequence>
                <xs:element ref="receitas:titulo"/>
                <xs:element ref="receitas:texto-introdutorio"  minOccurs="0"/>
                <xs:element ref="receitas:ilustração" minOccurs="0"/>
                <xs:choice maxOccurs="unbounded" minOccurs="0">
                    <xs:element ref="receitas:receita"/>
                    <xs:element ref="receitas:sub-seção"/>
                </xs:choice>
            </xs:sequence>
        </xs:complexType>
    </xs:element>
    
    <xs:element name="parte">
        <xs:complexType>
            <xs:sequence>
                <xs:element ref="receitas:titulo"/>
                <xs:element ref="receitas:texto-introdutorio"  minOccurs="0"/>
                <xs:element ref="receitas:ilustração" minOccurs="0"/>
                <xs:choice maxOccurs="unbounded" minOccurs="0">
                    <xs:element ref="receitas:receita"/>
                    <xs:element ref="receitas:seção"/>
                </xs:choice>
            </xs:sequence>
        </xs:complexType>
    </xs:element>
    <xs:element name="receitas">
        <xs:complexType>
            <xs:sequence>
                <xs:element ref="receitas:cabecalho"/>
                <xs:choice>
                    <xs:element ref="receitas:parte" maxOccurs="unbounded" />
                    <xs:element ref="receitas:seção" maxOccurs="unbounded" />
                </xs:choice>
            </xs:sequence>
        </xs:complexType>
    </xs:element>

    <xs:element name="passo">
        <xs:complexType>
            <xs:sequence>
                <xs:element ref="receitas:ingredienteRef"/>
            </xs:sequence>
            <xs:attribute name="id" type="xs:ID"/>
            <xs:attribute name="ilustração" type="xs:anyURI"/>
        </xs:complexType>
    </xs:element>
</xs:schema>

=== bmarrao/mestrado/PDE/Prática/Trabalho/exemploXSD2.xml
<?xml version="1.0" encoding="ISO-8859-1"?>
<receitas
        xmlns="trabalhoPDE"
        xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
        xsi:schemaLocation="trabalhoPDE receitas.xsd">
    <cabecalho>
        <titulo>Sobremesas Italianas</titulo>
        <autor>Breno Fernando Guerra Marrão</autor>
        <data-publicacao>
            2023-10-18
        </data-publicacao>
    </cabecalho>
    <seção>
        <titulo>Sobremesas do sul italiano</titulo>
        <texto-introdutorio>Nesta parte iremos abordar sobremesas que pertencem ao sul italiano</texto-introdutorio>
        <receita>
            <nome>Canoli</nome>
            <calorias>100</calorias>
            <categoria>sobremesa</categoria>
            <dificuldade>simples</dificuldade>
            <tempo>lento</tempo>
            <custo>barato</custo>
            <ilustração>./images/canoli</ilustração>
            <ingredientes>
                <ingrediente id="pistachio" quantidade="1" unidade-medida="chavena">
                    pistachio
                </ingrediente>
                <ingrediente id="sal">
                    sal
                </ingrediente>
                <ingrediente id="açucar" quantidade="4" unidade-medida="colher">
                    açucar
                </ingrediente>
                <ingrediente id="ovos" quantidade="2">
                    ovos
                </ingrediente>
                <ingrediente id="oleo-vegetal">
                    Óleo vegetal
                </ingrediente>
                <ingrediente id="canela" quantidade="1" unidade-medida="colher">
                    canela
                </ingrediente>
                <ingrediente id="vinho-marsala" quantidade="3" unidade-medida="colher">
                    vinho-marsala
                </ingrediente>
                <ingrediente id="farinha-trigo-sem-fermento" quantidade="2" unidade-medida="chavenas">
                    farinha de trigo sem fermento
                </ingrediente>
                <ingrediente id="queijo-creme" quantidade="250" unidade-medida="gramas">
                    quejo creme
                </ingrediente>
                <ingrediente id="ricotta" quantidade="500" unidade-medida="gramas">
                    ricotta
                </ingrediente>
            </ingredientes>
            <instruções>
                <texto-instrução>

                1. Para fazer a massa numa batedeira misture 2 chávenas e meia de <ingredienteRef
                    ref="farinha-trigo-sem-fermento"/> com <ingredienteRef ref="açucar"/>. Adicione 1 <ingredienteRef
                    ref="ovos"/> e 3 c. de <ingredienteRef ref="oleo-vegetal"/>.
                2. Utilize o acessório de massa para bater e, de seguida, adicione 1 c. de <ingredienteRef ref="canela"/> e 3 c. de sopa de <ingredienteRef
                    ref="vinho-marsala"/>. Bata novamente.
                3. Coloque a massa numa superfície coberta com <ingredienteRef ref="farinha-trigo-sem-fermento"/> e trabalhe-a até ficar com uma espessura de cerca de 0,5cm. Corte-a em discos de 10 a 15 cm de diâmetro.
                4. Com a ajuda de um cilindro de cannoli, enrole a massa à sua volta e com 1 clara de <ingredienteRef
                    ref="ovos"/> cole a ponta. Aqueça óleo numa frigideira e coloque os cannolis para fritar. Retire e coloque num prato com papel absorvente.
                5. Recheio: Enquanto arrefecem, numa taça coloque 500g de ricotta, 250g de queijo creme e 4 c. de sopa de açúcar em pó. Misture tudo.
                6. Dentro de um prato coloque <ingredienteRef ref="pistachio"/> grosseiramente picados com uma pitada de <ingredienteRef
                    ref="sal"/>. Num saco de pasteleiro coloque a mistura de <ingredienteRef ref="queijo-creme"/> e recheie o interior dos cannolis. Passe as pontas pelo prato com os<ingredienteRef ref="pistachio"/>.
                7. Polvilhe, no final, com <ingredienteRef ref="açucar"/> em pó.
                    ------ Posso também referenciar outras receitas <receitaRef ref="receita-teste"/>
                </texto-instrução>
            </instruções>
        </receita>
        <receita id="receita-teste">
            <nome>Nova receita de teste</nome>
            <ingredientes>
                <ingrediente id="teste">
                    teste
                </ingrediente>
            </ingredientes>
            <instruções>
                <passo>
                </passo>
            </instruções>
        </receita>

    </seção>
</receitas>

=== bmarrao/mestrado/PDE/Prática/Trabalho/exemploXSD1.xml
<?xml version="1.0" encoding="ISO-8859-1"?>
<receitas
        xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
        xsi:noNamespaceSchemaLocation="receitas.xsd">
    <cabecalho>
        <titulo>Livro de receitas do Breno</titulo>
        <titulo>Validação?</titulo>
        <autor>Breno Fernando Guerra Marrão</autor>
        <autor>Se quiser posso adicionar outros autores</autor>
        <data-publicacao>
            2023-10-18
        </data-publicacao>
        <resumo>
            Esse é o resumo opcional
        </resumo>
    </cabecalho>

    <parte >
        <titulo>Comida italiana</titulo>
        <texto-introdutorio>Esse é o texto-introdutorio opcional</texto-introdutorio>
        <ilustração>uri</ilustração>
        <receita id ="1">
            <nome>
                Spaghetti Bolonhesa
            </nome>
            <ilustração>"./images/spaghetti"</ilustração>
            <dificuldade>simples</dificuldade>
            <categoria>prato-principal</categoria>
            <custo>barato</custo>
            <tempo>medip</tempo>

            <!-- aqui irei adicionar uma receita como exemplo -->
            <ingredientes>
                <ingrediente id="3">
                    <nome>
                        spaghetti
                    </nome>
                    <!-- Opcional -->

                    <quantidade>
                        100
                    </quantidade>
                    <!-- Opcional -->
                    <unidade-medida>
                        gramas
                    </unidade-medida>
                </ingrediente>
                <ingrediente  id ="4">
                    <nome>Molho </nome>
                    <quantidade>100</quantidade>
                    <unidade-medida>ml</unidade-medida>
                </ingrediente>
            </ingredientes>
            <instruções >
                Para fazer o molho
                <passo id="fazer-molho">
                    Aquecer o <ingredienteRef ref="4"/>
                </passo>
                Para fazer a massa
                <passo id="fazer-massa">
                    Cozinhar o <ingredienteRef ref="3"/>
                </passo>
                Para fazer o molho
                <passo id="juntar-massa-molho">
                    Juntar <ingredienteRef ref="3"/> e <ingredienteRef ref="4"/>
                </passo>
            </instruções>
        </receita>
        <seção>
            <!-- ainda posso opcionalmente adicionar uma seção -->
            <titulo>
                Comida de Roma
            </titulo>
            <receita>
                <nome>Spaghetti Alfredo</nome>
                <ingredientes >
                    <ingrediente id="5">
                        <nome>
                            spaghetti
                        </nome>
                        <!-- Opcional -->

                        <quantidade>
                            100
                        </quantidade>
                        <!-- Opcional -->
                        <unidade-medida>
                            gramas
                        </unidade-medida>
                    </ingrediente>
                    <ingrediente  id ="6">
                        <nome>Molho </nome>
                        <quantidade>100</quantidade>
                        <unidade-medida>ml</unidade-medida>
                    </ingrediente>
                </ingredientes>
                <instruções>
                    <passoRef ref="fazer-molho"/>
                    <passoRef ref="fazer-massa"/>
                </instruções>
            </receita>

            <sub-seção>
                <titulo>Sobremesas</titulo>
                <receita id="tiramisu"   >
                    <nome>
                        tiramisu
                    </nome>
                    <tempo>lento</tempo>
                    <custo>barato</custo>
                    <categoria>sobremesa</categoria>
                    <dificuldade>dificil</dificuldade>
                    <ilustração>./images/tiramisu</ilustração>
                    <ingredientes >
                        <ingrediente id="cafe">
                            <nome>cafe</nome>
                            <quantidade>100</quantidade>
                            <unidade-medida>ml</unidade-medida>
                        </ingrediente>
                        <ingrediente id="biscoito">
                            <nome>biscoito champangne</nome>
                            <quantidade>1</quantidade>
                            <unidade-medida>pacotes</unidade-medida>
                        </ingrediente>
                        <ingrediente id="açucar"/>
                        <ingrediente id="leite"/>
                        <ingrediente id="gemas">
                            <nome>gemas</nome>
                            <quantidade>
                                3
                            </quantidade>
                        </ingrediente>
                        <ingrediente id="chocolate em po"/>
                        <ingrediente id="mascarpone">
                            <nome>mascarpone</nome>
                            <quantidade>500</quantidade>
                            <unidade-medida>gramas</unidade-medida>
                        </ingrediente>
                    </ingredientes>
                    <instruções>
                        <passo>
                            Bata o <ingredienteRef ref="leite"/> na batedeira até obter um chantilly firme.
                        </passo>
                        <passo>
                            Reserve
                        </passo>
                        <passo>
                            Bata o <ingredienteRef ref="açucar"/> com as <ingredienteRef ref="gemas"/> e o conhaque por 3 minutos.
                        </passo>
                        <passo>
                            Acrescente o chantilly, o <ingredienteRef ref="mascarpone"/> e misture bem.
                        </passo>
                        <passo>
                            Molhe rapidamente os <ingredienteRef ref="biscoito"/> no <ingredienteRef ref="cafe"/> (um a um) e coloque em um refratário formando uma camada, coloque por cima uma camada do creme, faça mais uma camada de <ingredienteRef ref="biscoito"/> molhados no <ingredienteRef ref="cafe"/> e por último mais uma camada de creme.
                        </passo>
                        <passo>
                            Para finalizar polvilhe <ingredienteRef ref="chocolate em po"/> em pó amargo.
                        </passo>
                        <passo>
                            Leve à geladeira por no mínimo 3 horas e sirva.
                        </passo>

                    </instruções>
                </receita>
            </sub-seção>
        </seção>
    </parte>

</receitas>
